# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_wnsdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcmdevice',
            name='is_fcm_device',
            field=models.BooleanField(default=False, help_text='Does this device use the React App?'),
        ),
    ]
